### ISSUE TITLE
Calendar not showing events when navigating from initial load or filtering

### ISSUE THREAD

**Issue by selby14** [DNNCommunity/DNN.Events#15] opened 2015-09-15 15:24 UTC
The initial load of the calendar seems to work fine. All events are displayed as expected, but when we navigate to a different month or filter by location no events are displayed even when we navigate back to the starting month and/or location. Since I am not seeing anyone else with this issue, I am assuming it has something to do with our event module settings or our DNN version. Has anyone had this issue or have any ideas on what settings I may need to adjust to fix this issue? You can see a live version of the problem at http://www3.pinellashomeless.org/Events 

Again, notice that that the events show fine initially but try to go to the next month and you will see there are no events shown and if you navigate back to the current month the calendar is still blank.

**Comment by EPTamminga** [comment] 2015-09-16 19:18
I expect that this can be related to javascript/skin conflict sith the DNN defaults. Have you tried the default DNN skin?

**Comment by selby14** [comment] 2015-09-16 20:27
I just tried with a default skin and have the same problem.

**Comment by EPTamminga** [comment] 2015-09-17 19:18
The calendar is based on a Telerik control. Is there something wrong with the Telerik dll version?

**Comment by rthoeni** [comment] 2015-10-15 14:28
I have the same problem (Fresh install DNN 7.4.2). I seen only this here in Event Detail:
<table cellspacing="2" cellpadding="3" border="0" width="90%" style="text-align:left"> <tbody> <tr valign="top"> < ; td class = "Subhead"> <span class="Head"> </ span> </ td> </ tr> </ tbody> < ; / table>
<table cellspacing="2" cellpadding="3" border="0" width="90%" style="text-align:left"> <tbody> < ; tr valign = "top"> <td class="SubHead" style="width:35%"> <span class="SubHead"> </ span> </ td> <span <span class="normal"> [IFTIMEZONEDISPLAY] [/ IFTIMEZONEDISPLAY] </ span> </ td>: Createddatelabel </ td> </ tr> </ tbody> </ table>

In Week:
n. Chr. [. NOTALLDAYEVENT] [ALLDAYEVENT] 19 [. ALLDAYEVENT] 	n. Chr. [. NOTALLDAYEVENT] [ALLDAYEVENT] 19 [. ALLDAYEVENT]

**Comment by EPTamminga** [comment] 2015-11-04 14:47
I am not able to reproduce the problem. Tried various combinations of settings, categories, locations, etc.

**Comment by Alderside** [comment] 2015-12-05 01:59
Hi All,

I had a similar problem this week with events not appearing after navigating to a different date on the calendar and finally tracked down the problem. A full breakdown of the problem and the fix is included in the attached PDF at the end of this comment. If you don't want to read the full story then go into the 'settings' - 'General settings' tab of the Events module. Under 'Look and Feel' there are two settings to be careful of, 'Enable Category Select' and 'Enable Location Select'. Be sure to leave these set to 'Do Not Display' if you do not have any entries on your category List or Locations List.

Thanks to the DNNEvents team for their work over the years 'maturing' it into an excellent module.
 
Cheers 
Bryn
[BrynSmith_DnnEventsNotAppearingAnswer.pdf](https://github.com/DNNCommunity/DNN.Events/files/52692/BrynSmith_DnnEventsNotAppearingAnswer.pdf)

**Comment by EPTamminga** [comment] 2015-12-05 09:54
Tnx for the feedback on your debugging! This opens an option to solve it in an upcoming release...

Met vriendelijke groet,
Ernst Peter Tamminga

Op 5 dec. 2015 om 02:59 heeft Alderside <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Hi All,

I had a similar problem this week with events not appearing after navigating to a different date on the calendar and finally tracked down the problem. A full breakdown of the problem and the fix is included in the attached PDF at the end of this comment. If you don't want to read the full story then go into the 'settings' - 'General settings' tab of the Events module. Under 'Look and Feel' there are two settings to be careful of, 'Enable Category Select' and 'Enable Location Select'. Be sure to leave these set to 'Do Not Display' if you do not have any entries on your category List or Locations List.

Thanks to the DNNEvents team for their work over the years 'maturing' it into an excellent module.

Cheers
Bryn
BrynSmith_DnnEventsNotAppearingAnswer.pdf<https://github.com/DNNCommunity/DNN.Events/files/52692/BrynSmith_DnnEventsNotAppearingAnswer.pdf>

—
Reply to this email directly or view it on GitHub<https://github.com/DNNCommunity/DNN.Events/issues/15#issuecomment-162126284>.




CEO
[XCESS expertise center b.v.]<https://www.xcess.nl/>    XCESS expertise center b.v.
Storkstraat 19
3833 LB Leusden, NL
I www.xcess.nl<https://www.xcess.nl>    M
D
T
E

+31-6-21564750
+31-33-4335101
+31-33-4335151
ernst.peter.tamminga@xcess.nl




________________________________

Dit e-mail bericht is alleen bestemd voor de geadresseerde, verstrekking aan en gebruik door anderen is niet toegestaan. Indien u niet de geadresseerde bent, wordt u vriendelijk verzocht de verzender hiervan op de hoogte te stellen en het bericht te verwijderen. In verband met de elektronische verzending kunnen aan de inhoud van dit bericht geen rechten worden ontleend. Tenzij schriftelijk anders is overeengekomen, zijn op al onze rechtsbetrekkingen de XCESS leveringsvoorwaarden<https://www.xcess.nl/Portals/0/Downloads/%5bXCESS%5d%20Algemene%20Leveringsvoorwaarden08052008NL.pdf> van toepassing. Deze zijn gedeponeerd bij de Kamer van Koophandel Amersfoort onder nummer 31047117 en bij de griffie van de arrondissementsrechtbank te Amsterdam onder nummer 36/2003 en worden op verzoek toegezonden. Toepasselijkheid van eventuele inkoop- of andere voorwaarden van opdrachtgever dan wel van derden wordt dan ook uitdrukkelijk van de hand gewezen door XCESS.

**Closed** 2018-07-12 05:16 UTC
Labels: bug
