### ISSUE TITLE
"Email this event to me" not working

### ISSUE THREAD

**Issue by chadwixk** [DNNCommunity/DNN.Events#170] opened 2019-03-07 16:54 UTC
## Describe the bug
DNN 9.2.2 Events 7.0.2

## Screenshots
When I click on this:
![image](https://user-images.githubusercontent.com/5115308/53973738-87ee0e00-40be-11e9-9bb2-ce6b1eb7e650.png)

Client Side Error in Console:
![image](https://user-images.githubusercontent.com/5115308/53973873-cf749a00-40be-11e9-93cb-0fe671e1bfac.png)

## Error log
```
AbsoluteURL /Default.aspx DefaultDataProvider DotNetNuke.Data.SqlDataProvi 
AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:ea08eac0-7164-4ffd-8d43-e24643eaa392
AssemblyVersion:9.2.2
PortalId:0
UserId:1
TabId:34
RawUrl:/Calenda/ModuleID/386/ItemID/199/mctl/EventDetails
Referrer:https://mysite.com/Calendar/ModuleID/386/ItemID/199/mctl/EventDetails
UserAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
ExceptionHash:h5jnT89jqGyW3OqQURW0KmKf3K8=
Message:startIndex cannot be larger than length of string. Parameter name: startIndex
StackTrace:
InnerMessage:startIndex cannot be larger than length of string. Parameter name: startIndex
InnerStackTrace:
at System.String.Substring(Int32 startIndex, Int32 length) at DotNetNuke.Modules.Events.VEvent.CreateiCal(Int32 iTabID, Int32 iModuleID, Int64 iItemID, Int32 socialGroupId, String iCategoryName, Int32 iCategoryID, String iLocationName, Int32 iLocationID, String calname) at DotNetNuke.Modules.Events.EventDetails.cmdEmail_Click(Object sender, EventArgs e) at System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e) at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument) at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
```

**Comment by EPTamminga** [comment] 2019-03-12 14:49
I cannot reproduce this on Events 07.00.03, So I assume it is solved in that release.
![image](https://user-images.githubusercontent.com/5859855/54209598-5a4dfe00-44de-11e9-8c08-34f56b5d542c.png)

**Comment by EPTamminga** [comment] 2019-03-12 14:49
I cannot reproduce this on Events 0.7.00.03, so I assume it is resolved in that release.

![image](https://user-images.githubusercontent.com/5859855/54209640-6934b080-44de-11e9-88e4-c2f8ad39c3cc.png)

**Closed by EPTamminga** 2019-03-12 14:49 UTC
