### ISSUE TITLE
iCal Export for non-recurring events not working

### ISSUE THREAD

**Issue by chandins** [DNNCommunity/DNN.Events#152] opened 2018-10-15 07:32 UTC
## Describe the bug
When trying to export the iCal for a non-recurring event, the below exception is thrown:
[NullReferenceException: Object reference not set to an instance of an object.]
   DotNetNuke.Modules.Events.VEvent.CreatevTimezones(DateTime dtStartDate, DateTime dtEndDate) +379
   DotNetNuke.Modules.Events.VEvent.CreateiCal(Int32 iTabID, Int32 iModuleID, Int64 iItemID, Int32 socialGroupId, String iCategoryName, Int32 iCategoryID, String iLocationName, Int32 iLocationID, String calname) +3355
   DotNetNuke.Modules.Events.VEvent.ProcessVCalRequest(HttpContext inContext) +1298
   DotNetNuke.Modules.Events.EventVCal.Page_Load(Object sender, EventArgs e) +54
   System.Web.Util.CalliEventHandlerDelegateProxy.Callback(Object sender, EventArgs e) +51
   System.EventHandler.Invoke(Object sender, EventArgs e) +0
   System.Web.UI.Control.OnLoad(EventArgs e) +92
   System.Web.UI.Control.LoadRecursive() +54
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

## To Reproduce
1. Select an existing non-recurring event to open the Event Details
2. Click on 'Export' to export the iCal
3. See exception thrown

## Expected behavior
An iCal for the event should be downloaded

## Additional context
I am using Events module version 07.00.03, and DNN version 9.2.0. I upgraded the module from version 06.03.00

**Comment by EPTamminga** [comment] 2019-03-14 15:22
I cannot reproduce this on my latest version of Events 07.00.03, so I assume it is resolved in the latest version

**Closed by EPTamminga** 2019-03-14 15:22 UTC
