### ISSUE TITLE
DotNetNuke.Web.Deprecated not present after upgrades but DotNetNuke.Website.Deprecated IS present

### ISSUE THREAD

**Issue by moorecreative** [DNNCommunity/DNN.Events#193] opened 2019-08-14 02:54 UTC
## Describe the bug
A client DNN instance was upgraded from DNN 8 to DNN 9. The DNN Events module installed was at 6.2.2 and after the upgrade to DNN 9, displayed the expected error messages. We upgraded insteps (just in case it was necessary) to
DNN Events 6.3.1
DNN Events 7.0.0
DNN Events 7.0.4

Now, after the last/latest update, we still see an error message of
Error: Events is currently unavailable. DotNetNuke.Services.Exceptions.ModuleLoadException: Could not load file or assembly 'DotNetNuke.Web.Deprecated' or one of its dependencies. The system cannot find the file specified. ---> System.Web.HttpParseException: Could not load file or assembly 'DotNetNuke.Web.Deprecated' or one of its dependencies. The system cannot find the file specified. ---> System.Web.HttpParseException: Could not load file or assembly 'DotNetNuke.Web.Deprecated' or one of its dependencies. The system cannot find the file specified. ---> 

Looking within the BIN folder, I can see a file named
"DotNetNuke.Website.Deprecated.dll"
but not one named
"DotNetNuke.Web.Deprecated.dll"

I then started from a new DNN 9x instance and installed the DNN Events 6.2.2 in that location, and then stepped up through the upgrades in the same manner, finishing with 7.0.4.

The result in this location was that the "DotNetNuke.Web.Deprecated.dll" was present in the Bin folder.

I am assuming that the previous environment was slightly different than the average, and this created an issue that made the end upgrades different than with a vanilla DNN 9 instance.

Once this file was added to the Bin folder, the module worked perfectly.

**Comment by valadas** [comment] 2019-08-15 01:24
Hey there, DotNetNuke.Web.Deprecated.dll is distributed with Dnn Platform, the reason this file was missing should not be related to the module here... 

My guess is that something wrong happened in the Dnn 8 to Dnn 9 upgrade, can you reproduce on a clean 8>9 upgrade, maybe something specific to that site got in the way of some upgrade step for Dnn ?

**Comment by EPTamminga** [comment] 2019-08-16 13:04
When I browse some of the original DNN8x sites that I upgraded to DNN932 for test purposes locally  I can spot the file "DotNetNuke.Website.Deprecated.dll" there as well.
I tried to find the origin of those files, but that is unclear to me.

The dll details tell me that it is DNN9.3.2.

When I decompile both DLL's, the content is different.
"DotNetNuke.Website.Deprecated" contains more modules than "DotNetNuke.Web.Deprecated"

**Comment by EPTamminga** [comment] 2019-08-16 13:40
If I start with a clean DNN804 and upgrade that to DNN932, I get both the files
`DotNetNuke.Website.Deprecated.dll` and `DotNetNuke.Web.Deprecated.dll` in the bin folder of the upgraded site

The file `DotNetNuke.Website.Deprecated.dll` is located in the module zip install `DNNCE_Website.Deprecated_09.03.02_Install.zip` of the **DNN932 upgrade** pack

The file `DotNetNuke.Web.Deprecated.dll` is located in the module zip install `DNNCE_Website.Deprecated_09.03.02_Install.zip` of the **DNN932 install** pack.

The **upgrade** and the **install** zip of DNN932 thus have different contents in the module install zip of `DNNCE_Website.Deprecated_09.03.02_Install.zip` within the install\modules subfolder of the total zip.

I assume the install pack is correct, the upgrade pack not.

**Comment by valadas** [comment] 2019-08-16 18:42
I can shed some light on the differences between those two dlls:

DotNetNuke.Web.Deprecated is mostly the telerik wrappers and other deprecated stuff that some third party modules may still use.

DotNetNuke.Website.Deprecated contains methods pertaining to the old ControlPanel before the persona bar. Now this is needed only during an upgrade from pre-9 to 9 in order to be able to migrate custom old admin and host pages into the persona bar and that is why it is included only in the upgrade package, that part is normal.

Now the other one should be part of both upgrade and install, let me double-check that, if missed in 9.3.2 we need to make sure 9.4.x solves this build issue and update the recommened upgrade path to go directly from 9.1.1 to 9.4.x skipping 9.3.2. I am checking this now...

**Comment by valadas** [comment] 2019-08-16 18:48
I see DotNetNuke.Web.dll in 9.3.2 install and upgrade packages and 9.4.0 install and upgrade packages.

I see DotNetNuke.Website.Deprecated in 9.3.2 upgrade and 9.4.0 upgrade packages only.

**Comment by EPTamminga** [comment] 2019-08-19 09:37
So:
* The file `DotNetNuke.Website.Deprecated.dll` should/could be deleted after an upgrade to DNN9
* This issue can be closed?

**Comment by valadas** [comment] 2019-08-19 21:54
I am 99% sure about this, just not sure if it still contains stuff a third party module may need and is marked deprecated until it is officially removed in version x. I know code cleanup is undergoing in the platform and when we get to this one we should not only stop distributing it but also remove it in version x.

**Comment by valadas** [comment] 2019-08-19 22:08
Created this related issue here: https://github.com/dnnsoftware/Dnn.Platform/issues/2957

Now those methods where just moved into an assembly with the word deprecated in it's name. But the methods/properties did not get the [Obsolete] attribute somehow. This means, that 3rd party developers that would consume those methods/properties would not know yet this is deprecated. Also this is required for any upgrade from pre-dnn-9 to post-dnn-9, so we need to update the suggested upgrade path at the version where we decide to cut it out (say Dnn11, then it would not be possible to upgrade from 8 to 11 for instance).

**Comment by valadas** [comment] 2019-08-19 22:12
As for closing the issue, I have done several upgrades from multiple versions to multiple versions and I have not encountered this issue. At any rate, I will close this issue since even if we find this being a problem, it would need to be in the Platform repository. The only way I think that this module would delete the file would be in cleanup scripts and I do not see it listed there.

**Closed by valadas** 2019-08-19 22:12 UTC
