### ISSUE TITLE
Month View Date Control Not Working in 07.00.04

### ISSUE THREAD

**Issue by djamell** [DNNCommunity/DNN.Events#194] opened 2019-10-26 17:15 UTC
## Describe the bug
Running DNN 8.0.4 and Events 07.00.04 (fresh install, not upgraded).

I know this had been addressed recently, but it is not working for me.

When I use the date picker or manually type in the date, the screen refreshes, but the Month View doesn't change.

## To Reproduce
In the date field of the month view, enter a date by hand or using the dropdown selector the module refreshes but does not change month or selected day.

## Expected behavior
The calendar should move to that month and year and outline the day cell.

## Screenshots
You can see the module on this page:
http://dev.scottsebastianregionallibrary.com/Events

## Error log
Nothing in the Event Log

**Comment by djamell** [comment] 2019-11-16 12:25
I could no longer wait for an answer so I uninstalled 07.00.04 and installed 06.03.01.

**Comment by thabaum** [comment] 2019-11-26 19:14
I am hoping to maybe switch this to a JS Datepicker as DNN Events currently uses telerik currently am I correct in thinking about this one?

I have been looking at the code here a bit more as I wish to try to contribute here a little if I can however I am just me... I will get more fluent over time but it has taken years to get this far dont hold your breathe !! However I can help steer another developer in the right area to poke around and see if they can see something they can do a pull request for making any changes.  100% volunteer effort on all DNN platform and modules.  It is the wild west in a way.

**Comment by EPTamminga** [comment] 2019-11-27 08:20
One of my colleagues has been working on a JS replacement of the Telerik date control, not finished though. 
I tried to fix the current Telerik date picker but could not yet solve a strange error in debugging re a missing item "SelectedData", whereas the code references "SelectedDate". Still trying to figure it out.
BTW A standard date picker is not yet in DNN

**Comment by djamell** [comment] 2019-11-27 13:06
It works perfectly in 06.03.01.

**Comment by brbjr1** [comment] 2019-11-27 13:15
> One of my colleagues has been working on a JS replacement of the Telerik date control, not finished though.
> I tried to fix the current Telerik date picker but could not yet solve a strange error in debugging re a missing item "SelectedData", whereas the code references "SelectedDate". Still trying to figure it out.
> BTW A standard date picker is not yet in DNN

The problem is the event handler was not added on the EventMonth.ascx and EventWeek.ascx

month view fix:  https://github.com/brbjr1/DNN.Events/commit/89e5034986b84d3bff836e1662b47b4475de191c

week view fix:
https://github.com/brbjr1/DNN.Events/commit/2163c942ef4e8a55f3b0d3e2407747184762994e

**Comment by brbjr1** [comment] 2019-11-27 13:34
I just submitted a pull request to fix this

**Comment by thabaum** [comment] 2019-11-27 22:42
Nice ! Thanks for the fix and community contribution.  👍 

I always thought the future of DNN modules would be using React or js libraries the same as used inside the persona bar.  For now just making things work as expected would be awesome.

**Comment by valadas** [comment] 2019-11-29 09:13
> I always thought the future of DNN modules would be using React or js libraries the same as used inside the persona bar.

Well, hopefully not as in the persona bar :) Let's hope we can make this better. There are a lot of modules and we will need to move them away from webforms one day. But yeah, right now any fix is welcome at least. Also, there is no set rules on those other than we want to keep them upgradeable for sites that use them and want to upgrade Dnn without loosing all their content and having to switch to different modules. Depending on each maintainer (and some have no official maintainers), exactly how that moves away from webforms may be different per module.

**Comment by EPTamminga** [comment] 2020-02-04 07:25
Fixed in Events 07.00.05, available as (pre) release.

**Closed by EPTamminga** 2020-02-04 07:25 UTC
