### ISSUE TITLE
7.0.2 Bug - Change View

### ISSUE THREAD

**Issue by PeterCasper** [DNNCommunity/DNN.Events#105] opened 2018-07-12 08:27 UTC
G'day All,

Just a little one to start: When moving from a week view to a month view, the month show no entries. Moving one month forward then one back correctly displays the month's entries.

Peter C

**Comment by valadas** [comment] 2018-07-16 05:17
I cannot reproduce this issue. @PeterCasper can you provide more details.

Which Dnn version, do you get any errors either on screen, the browser console, the Dnn admin logs... etc. Any thing out of the normal settings, steps to reproduce from a clean install, etc.

**Comment by PeterCasper** [comment] 2018-07-16 10:46
Valadas,

I revisited the module & I cannot consistently repeat the problem. This is what I intermittently see:
https://youtu.be/sHOB4oPUAQk

Peter C

**Comment by EPTamminga** [comment] 2018-08-02 14:01
I tried it with Events 07.00.02, but I cannot reproduce it either. Closing issue. 
Please reopen if the problem resurfaces with the upcoming (07.00.03) release

**Closed by EPTamminga** 2018-08-02 14:01 UTC
Labels: Cannot reproduce
